-- Initial public content. Countries, stock and wallets require owner input.
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('hass','Avocado Hass','Ваш трафик под защитой','Защита от DDoS-атак и блокировок РКН. Стабильность сервисов, глобальная сеть и аналитика.

Обсудим вашу инфраструктуру и условия подключения в чате.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('ettinger','Avocado Ettinger','Офисная оркестрация нового поколения','Массовая закупка доменов и серверов. ИИ-адаптеры. Автоматизация NIC.RU. Регистрация и верификация аккаунтов.

Автоматизируйте повторяющиеся операции и управляйте инфраструктурой в одной экосистеме.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('rent','Аренда панели','Возможности Avocado на нужный срок','Арендуйте панель под задачи вашей команды. Защита, закупки и автоматизация в одной экосистеме.

Срок аренды, набор возможностей и стоимость согласуем в чате. Цена по запросу.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('home','Инфраструктура, которая работает на вас.','Защита, автоматизация и масштабирование в одной экосистеме.','Avocado объединяет защиту трафика, анти-DDoS, защиту от блокировок РКН, массовую закупку доменов и серверов, ИИ-адаптеры и автоматизацию NIC.RU.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('catalog','Инфраструктура под вашу задачу','Домены, серверы и прокси. Подберём конфигурацию и согласуем условия в чате.','Выберите направление. Страна, наличие и итоговая стоимость подтверждаются оператором перед выставлением счёта.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('countries','География вашей инфраструктуры','Нужная локация для вашего проекта.','Уточните страну и требования в чате. Мы проверим доступность и предложим подходящую конфигурацию.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('payment','Оплата криптовалютой','Без KYC и верификаций. Согласуйте удобную валюту и сеть в чате.','Обсудите услугу с оператором. Получите счёт с точной суммой, сетью и адресом кошелька. Переведите средства по реквизитам счёта и отправьте идентификатор транзакции в чат. После ручного подтверждения поступления мы выдадим услугу.

Поддержку выбранной криптовалюты и сети подтвердим перед оплатой. Сроки выдачи и условия согласуем до выставления счёта.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('news','Новости Avocado','Обновления продуктов и новости инфраструктуры.','Всё важное об экосистеме Avocado.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('contacts','Обсудим вашу задачу','Начните с разговора. Поможем выбрать решение.','Напишите в чат на сайте или в Telegram. Расскажите, какая инфраструктура нужна, и мы уточним детали.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('category-domains','Домены','Поиск, регистрация и массовая закупка доменов.','Расскажите о требованиях, географии и нагрузке. Подберём решение, проверим наличие и согласуем стоимость.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('category-vps','VPS','Виртуальные серверы под задачи вашего проекта.','Расскажите о требованиях, географии и нагрузке. Подберём решение, проверим наличие и согласуем стоимость.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('category-dedicated','Выделенные серверы','Физические серверы с индивидуальной конфигурацией.','Расскажите о требованиях, географии и нагрузке. Подберём решение, проверим наличие и согласуем стоимость.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('category-bulletproof','Bulletproof-хостинг','Новое направление. Подробности — после запуска.','Направление готовится к запуску. Напишите в чат, чтобы обсудить будущие возможности.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_pages(slug,title,summary,body,status,created_at,updated_at) VALUES('category-proxies','Прокси','Подбор прокси под географию и требования проекта.','Расскажите о требованиях, географии и нагрузке. Подберём решение, проверим наличие и согласуем стоимость.','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_products(slug,title,category,summary,body,price,price_currency,availability,country_codes,image,status,created_at,updated_at) VALUES('domains','Домены','domains','Поиск, регистрация и массовая закупка доменов.','Поиск, регистрация и массовая закупка доменов.','','USD','on_request','[]','','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_products(slug,title,category,summary,body,price,price_currency,availability,country_codes,image,status,created_at,updated_at) VALUES('vps','VPS','vps','Виртуальные серверы под задачи вашего проекта.','Виртуальные серверы под задачи вашего проекта.','','USD','on_request','[]','','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_products(slug,title,category,summary,body,price,price_currency,availability,country_codes,image,status,created_at,updated_at) VALUES('dedicated','Выделенные серверы','dedicated','Физические серверы с индивидуальной конфигурацией.','Физические серверы с индивидуальной конфигурацией.','','USD','on_request','[]','','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_products(slug,title,category,summary,body,price,price_currency,availability,country_codes,image,status,created_at,updated_at) VALUES('bulletproof','Bulletproof-хостинг','bulletproof','Новое направление. Подробности — после запуска.','Новое направление. Подробности — после запуска.','','USD','soon','[]','','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_products(slug,title,category,summary,body,price,price_currency,availability,country_codes,image,status,created_at,updated_at) VALUES('proxies','Прокси','proxies','Подбор прокси под географию и требования проекта.','Подбор прокси под географию и требования проекта.','','USD','on_request','[]','','published','1789209821279','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('telegramUrl','https://t.me/avogurubot','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('email','','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('chatApiBase','https://avocado-chat.avocado-chat-worker.workers.dev','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('wallets','[]','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('paymentTerms','','1789209821279');
INSERT OR IGNORE INTO cms_settings(key,value,updated_at) VALUES('refundTerms','','1789209821279');
